# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: template
  description: Template for Terraform Components
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
  allow_auto_merge: true

rulesets:
  - name: Merge Queue
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - "~DEFAULT_BRANCH"
        exclude: []
    rules:
      - type: merge_queue
        parameters:
          check_response_timeout_minutes: 240
          grouping_strategy: ALLGREEN
          max_entries_to_build: 5
          max_entries_to_merge: 5
          merge_method: SQUASH
          min_entries_to_merge: 1
          min_entries_to_merge_wait_minutes: 30
      - type: required_status_checks
        parameters:
          strict_required_status_checks_policy: false
          do_not_enforce_on_create: false
          required_status_checks:
            - context": "component / ci"          
