---
name: auto merge
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number'
        required: true
        type: string

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  automerge:
    runs-on: ['ubuntu-latest']
    name: "Auto merge"
    steps:
      - run: "gh pr merge ${{ inputs.pr_number }} --auto"
